import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

const repository = process.env.GITHUB_REPOSITORY;
const token = process.env.GITHUB_TOKEN;
const outputPath = process.env.BLOG_OUTPUT ?? "app/data/blog.generated.js";

if (!repository || !token) throw new Error("GITHUB_REPOSITORY and GITHUB_TOKEN are required.");

const headers = { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "X-GitHub-Api-Version": "2022-11-28" };

async function getIssues() {
  const issues = [];
  for (let page = 1; ; page += 1) {
    const url = new URL(`https://api.github.com/repos/${repository}/issues`);
    url.searchParams.set("state", "all");
    url.searchParams.set("labels", "blog");
    url.searchParams.set("per_page", "100");
    url.searchParams.set("page", String(page));
    const response = await fetch(url, { headers });
    if (!response.ok) throw new Error(`GitHub issues request failed: ${response.status} ${await response.text()}`);
    const pageIssues = await response.json();
    issues.push(...pageIssues.filter((issue) => !issue.pull_request));
    if (pageIssues.length < 100) return issues;
  }
}

function sections(body = "") {
  const values = {};
  let currentHeading;
  let currentValue = [];
  const save = () => {
    if (currentHeading) values[currentHeading] = currentValue.join("\n").trim();
  };
  for (const line of body.split("\n")) {
    if (currentHeading === "post body") {
      currentValue.push(line);
      continue;
    }
    const heading = line.match(/^#{2,3}\s+(.+?)\s*$/);
    if (heading) {
      save();
      currentHeading = heading[1].trim().toLowerCase();
      currentValue = [];
    } else if (currentHeading) {
      currentValue.push(line);
    }
  }
  save();
  return values;
}

function required(values, field, issue) {
  const value = values[field]?.trim();
  if (!value) throw new Error(`Issue #${issue.number} is missing ${field}.`);
  return value;
}

function parsePost(issue) {
  const values = sections(issue.body);
  const post = {
    slug: required(values, "slug", issue),
    title: required(values, "title", issue),
    excerpt: required(values, "excerpt", issue),
    date: required(values, "date", issue),
    category: required(values, "category", issue),
    readingTime: required(values, "reading time", issue),
    body: required(values, "post body", issue),
  };
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(post.slug)) throw new Error(`Issue #${issue.number} has an invalid slug: ${post.slug}`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(post.date) || Number.isNaN(Date.parse(`${post.date}T00:00:00Z`))) throw new Error(`Issue #${issue.number} has an invalid date: ${post.date}`);
  return post;
}

const issues = await getIssues();
const posts = issues.filter((issue) => issue.labels.some(({ name }) => name.toLowerCase() === "published")).map(parsePost).sort((a, b) => b.date.localeCompare(a.date));
const slugs = new Set();
for (const post of posts) {
  if (slugs.has(post.slug)) throw new Error(`Duplicate published slug: ${post.slug}`);
  slugs.add(post.slug);
}

const output = `// Generated by scripts/sync-blog.mjs. Edit the GitHub Issue instead.\nexport const blogPosts = ${JSON.stringify(posts, null, 2)};\n`;
await mkdir(dirname(outputPath), { recursive: true });
let existing = "";
try { existing = await readFile(outputPath, "utf8"); } catch (error) { if (error.code !== "ENOENT") throw error; }
if (existing !== output) { await writeFile(outputPath, output); console.log(`Wrote ${posts.length} published post(s) to ${outputPath}.`); }
else console.log(`Blog data is already current (${posts.length} published post(s)).`);
